apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev
  # namespace: dev
spec:
  project: dev
  source:
    repoURL: https://github.com/si3mshady/argocd_3_env_deployment.git#dev
    # targetRevision: dev
    path: overlay/dev
  destination:
    server: https://api.elliottarnold.com
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stg
  # namespace: stg
spec:
  project: default
  source:
    repoURL: https://github.com/si3mshady/argocd_3_env_deployment.git#stg
    # targetRevision: stg
    path: overlay/stg
  destination:
    server: https://api.elliottlamararnold.com
    namespace: stg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod
  # namespace: prod
spec:
  project: prod
  source:
    repoURL: https://github.com/si3mshady/argocd_3_env_deployment.git#prod
    # targetRevision: prod
    path: overlay/prod
  destination:
    server: https://api.lamararnold.com
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
