apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev
  namespace: argocd
spec:
  project: dev
  source:
    repoURL: https://github.com/si3mshady/argocd_3_env_deployment.git
    targetRevision: HEAD
    path: overlay/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stg
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/si3mshady/argocd_3_env_deployment.git
    targetRevision: HEAD
    path: overlay/stg
  destination:
    server: https://kubernetes.default.svc
    namespace: stg
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod
  namespace: argocd
spec:
  project: prod
  source:
    repoURL: https://github.com/si3mshady/argocd_3_env_deployment.git
    targetRevision: HEAD
    path: overlay/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
